name: Random Word

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily, adjust the cron expression as needed
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update-file:
    runs-on: macos-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Random Word
        run: |
          HTTP_CONTENT=$(curl -s https://random-word-api.herokuapp.com/home)

      - name: Update File
        run: echo "$HTTP_CONTENT" > randomword.html

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions on behalf of Raven."
          git add randomword.html 
          git commit -m "Update file with HTTP content"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

